### ISSUE TITLE
Add acf-medium-editor to list of medium-editor integrations?

### ISSUE THREAD

**Issue by nmielnik** [Hube2/acf-medium-editor#16]
@Hube2 I just stumbled upon your repo here and thought was a really awesome integration you've built.

We have a section in our Wiki where we call out all the wrappers / integrations people have built for medium-editor...would you mind adding your app to there?

You can add it directly to there Wiki [here](https://github.com/yabwe/medium-editor/wiki/Wrappers-and-Integration).

I want to look into a way to include links to these integrations within the repo itself as well, instead of just the Wiki, but until that happens you should definitely call out your application.

Great work, and thanks for you work with medium-editor!

**Comment by Hube2** [comment]
Done

**Comment by nmielnik** [comment]
Awesome, thanks!

**Comment by Hube2** [comment]
I can use the advertisement, or at least it can't hurt. I should probably be selling the WP plugin but that's just a PITA. But it's one them many that I've created that I think will eventually be popular. I was tired of making clients try to put markdown into a textarea because I'd have to refresh their memory every time they wanted to change something. WordPress can be extremely limiting at times and I think that this will remove some of those limits. We'll see.
