### ISSUE TITLE
Medium Editor not displaying formatting in admin area

### ISSUE THREAD

**Issue by RobertFlambour** [Hube2/acf-medium-editor#26]
We appear to be having an issue with this wonderful plugin where some of the text formatting is not showing in the backend.

If check the see the image, you can see that H2, and the Unordered list are not formatted correctly.
All plugins are disabled, using latest ACF Pro Version 5.7.8 and latest Medium Editor Version 2.4.4 on default theme.

![issues](https://user-images.githubusercontent.com/38284466/49770884-a9975d80-fd3a-11e8-9618-02a0d66914f7.jpg)

**Comment by Hube2** [comment]
The formatting of content in the editor is controlled by the WP admin style sheet. For example the H2 element is using
```
#poststuff .stuffbox > h3, #poststuff h2, #poststuff h3.hndle {
    font-size: 14px;
    padding: 8px 12px;
    margin: 0;
    line-height: 1.4;
}
```
In order to change this you would need to add a custom style sheet to the admin and override WP

```
#poststuff .medium-edtor-element h2 {
    /* your styles here */
}
```
Since I cannot possibly satisfy everyone when it comes to the styling of the content in the editor I have not added any styles to content in the medium editor element for the wp medium editor theme that I've created. The only thing I've really adjusted is the styling of the box and the buttons so that it matches WP styling for these types of elements. Unlike WP and tinyMCE, medium editor does not provide a way to add editor specific styles. Also, unlike tinyMCE, medium editor does not use an ifrrame that allows styling to be independent of the WP admin styles.

I can look at adding the ability to allow adding of a custom stylesheet in the theme for medium editor that would automatically enqueue the stye sheet if it exists.

**Comment by Hube2** [comment]
I added the ability to add a custom css file to your theme folder and have it automatically included. See the readme for more info.
