### ISSUE TITLE
Implement custom extension (tab)

### ISSUE THREAD

**Issue by yepecece** [Hube2/acf-medium-editor#31]
Hi, 

I would like to implement a custom extension which is showcased here:
https://github.com/yabwe/medium-editor/issues/894#issuecomment-260194623

If I add it to the input.js it works but it is not a safe way to implement it.

What would be the correct way to add this to your plugin?

Thanks for your help.

**Comment by Hube2** [comment]
The best way to do this without editing the code of this plugin.

save the JS as a file somewhere in your theme, for example "medium-editor-tab-extension.js"

Create an action
```
add_action('acf/input_admin_enqueue_scripts', 'enqueue_medium_tab_extenstion') 
function enqueue_medium_tab_extenstion() {
  $handle = 'medium-editor-tab-extenstion';
  $src = 'path/to/script/file';  // probably using get_template_directory_uri() or get_stylesheet_directory_uri()
  $dep = array('medium-editor'); // depends on script for this plugin
  wp_enqueue_script($handle, $src, $dep);
}
```

**Comment by yepecece** [comment]
Thanks for your help.

I managed to enqueue the script. This is the correct action
`add_action('acf/input/admin_enqueue_scripts', 'enqueue_medium_tab_extenstion');`

The problem is how to add the extension to the $custom_buttons array that is used in your plugin when initiating MediumEditor.
Normally the extension is used as such:
`var tabIndent = new TabIndent();
var editor = new MediumEditor('.editable', {
    buttonLabels: 'fontawesome',
    extensions: {
      'tabIndent': tabIndent,
    },
})`

Thanks

**Comment by Hube2** [comment]
I really don't want to do a lot of work on this plugin. Not sure how closely you've been following Medium Editor but I'm not altogether sure it's going to be around much longer. If it goes away then this add on for ACF will also go away. As I understand it there are some issues with newer browsers and it needs a lot of work to get it fixed.

I also do not want to add another extension to this plugin.

I've been looking at possible ways to make this, the best thing that I can think of to do is to add a filter to allow the src value of wp_enqueue_script() to be overwritten. This would allow a script in the theme to be loaded instead of the script in this pluign. You could then copy and alter input.js. Somewhere before line 73
```
var editor = new MediumEditor($selector, $object);
```
You can add the extension to `$extensions` and add the custom button to `$custom_buttons` or otherwise modify `$object` to do whatever you want. 

Unless there is a major update to Medium Editor or Medium Button, I don't see that my input.js file is going to change.

**Comment by yepecece** [comment]
Thanks for the help.

I did not know Medium Editor would be discontinued. 
I will go ahead and allow your advice.
Also, do you know any other similar tools?

Thanks again.

**Comment by Hube2** [comment]
I don't know that it will be discontinued, but they are having trouble locating people to maintain it and it's having some issues. I'm just saying that it's future is uncertain.

I'll add the filter as soon as I am able.

**Comment by Hube2** [comment]
example of use
```
add_filter('acf-medium-editor-script-src', 'my_override_medium_editor_input_js', 10, 1)
function my_override_medium_editor_input_js($script_src) {
  $script_src= get_template_directory_uri().'/path/to/custom/input.js';
  return $script_src;
}
```

**Comment by yepecece** [comment]
Thanks,

it works perfectly.
